project:
  type: website

website:
  title: "GPS Data Consulting"
  navbar:
    logo: images/logo_stacked.png
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - services.qmd

format:
  html:
    theme: 
      - custom_theme.scss
    css: styles.css
    toc: true

editor: visual

