project:
  type: website
  output-dir: docs

website:
  title: "GPS Data Consulting"
  navbar:
    logo: images/logo_stacked.png
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: services.qmd
        text: Services

format:
  html:
    theme:
      - default
      - custom_theme.scss
    css: styles.css
    toc: true

editor: visual

